routes/web.php
Route::get('/modalidad/buscar/{id?}', 'modalidadController@buscar')->name('modalidadBuscar')->middleware('auth');

Route::get('/aula', 'aulaController@show')->name('aula')->middleware('auth');
Route::post('/aula/create', 'aulaController@create')->middleware('auth');
Route::put('/aula/update/{id?}', 'aulaController@update')->middleware('auth');
Route::get('/aula/buscar/{id?}', 'aulaController@buscar')->name('aulaBuscar')->middleware('auth');
Route::put('/aula/cambiarEstado/{id?}', 'aulaController@cambiarEstado')->middleware('auth');

Route::get('/responsable', 'responsableController@show')->name('responsable')->middleware('auth');
Route::post('/responsable/create', 'responsableController@create')->middleware('auth');
Route::put('/responsable/update/{id?}', 'responsableController@update')->middleware('auth');
Route::get('/responsable/buscar/{id?}', 'responsableController@buscar')->name('responsableBuscar')->middleware('auth');

Route::get('/curso', 'cursoController@show')->name('curso')->middleware('auth');
Route::get('/curso/{id?}', 'cursoController@showPorIdioma')->name('cursoShowIdioma')->middleware('auth');
Route::get('/curso/estado/{estado?}/{id?}', 'cursoController@showPorEstado')->name('cursoShow2')->middleware('auth');
Route::post('/curso/create', 'cursoController@create')->middleware('auth');
Route::get('/curso/bus/idioma','cursoController@busquedaSelectIdioma');
Route::get('/curso/bus/modalidad','cursoController@busquedaSelectModalidad');
Route::get('/curso/bus/categoria','cursoController@busquedaSelectCategoria');
Route::get('/curso/bus/selectformulario','cursoController@llenarSelectFormulario');
Route::get('/curso/buscarHorarios/{id?}', 'cursoController@buscarHorarios')->middleware('auth');;
Route::put('/curso/cambiarEstado/{id?}', 'cursoController@cambiarEstado')->middleware('auth');
Route::put('/curso/actualizarPrecio', 'cursoController@actualizarPrecio')->middleware('auth');
Route::post('/curso/modificarHorarios', 'cursoController@modificarHorarios')->middleware('auth');
Route::post('/curso/createCategoria', 'cursoController@createCategoria')->middleware('auth');
Route::put('/curso/cambiarEstadoCurso/{id?}', 'cursoController@cambiarEstadoCurso')->middleware('auth');
Route::get('/cursoNiveles/{id?}', 'cursoController@showNiveles')->name('cursoShowNiveles')->middleware('auth');

Route::put('/nivel/cambiarEstado/{id?}', 'nivelController@cambiarEstado')->middleware('auth');
Route::post('/nivel/create', 'nivelController@create')->middleware('auth');

Route::get('/periodo', 'periodoController@show')->name('periodo')->middleware('auth');
Route::post('/periodo/create', 'periodoController@create')->middleware('auth');
Route::put('/periodo/update/{id?}', 'periodoController@update')->middleware('auth');
Route::get('/periodo/buscar/{id?}', 'periodoController@buscar')->name('periodoBuscar')->middleware('auth');
Route::put('/periodo/cambiarEstado/{id?}', 'periodoController@cambiarEstado')->middleware('auth');
Route::get('/periodo/filtrar/{anho?}/{nperiodofiltro?}', 'periodoController@filtrar')->name('periodoFiltrar')->middleware('auth');
Route::get('/importar', 'periodoController@showImportarBlade')->name('importar')->middleware('auth');
Route::post('/importar/obtenerGrupos', 'periodoController@obtenerGrupos')->middleware('auth');
Route::post('/importar/obtenerEstudiantes', 'periodoController@obtenerEstudiantes')->name('importarEstudiantes')->middleware('auth');
Route::post('/importar/importarGrupo', 'periodoController@importarGrupo')->name('importarGrupo')->middleware('auth');


Route::get('/grupos', 'grupoController@show')->name('grupo')->middleware('auth');
Route::get('/gruposExample', 'grupoController@showEditable')->name('grupoShowEditable')->middleware('auth');
Route::post('/grupos/create', 'grupoController@create')->middleware('auth');
Route::put('/grupos/update/{idgrupos?}', 'grupoController@update')->middleware('auth');
Route::get('/grupos/categorias/{idcurso?}', 'grupoController@buscarCategorias')->middleware('auth');
Route::put('/grupos/categoriasPeriodoFiltro/{idcurso?}', 'grupoController@buscarCategoriasPeriodofiltro')->middleware('auth');
Route::get('/grupos/niveles/{idcursocategorias?}', 'grupoController@buscarNiveles')->middleware('auth');
Route::put('/grupos/filtrar', 'grupoController@filtrar')->middleware('auth');
Route::get('/grupos/busquedaAula/{texto?}', 'grupoController@busquedaAula')->middleware('auth');
Route::put('/grupos/updateAula/{idgrupos?}', 'grupoController@updateAula')->middleware('auth');
Route::get('/grupos/busquedaDocente/{texto?}', 'grupoController@busquedaDocente')->middleware('auth');
Route::put('/grupos/updateDocente/{idgrupos?}', 'grupoController@updateDocente')->middleware('auth');
Route::put('/grupos/periodos', 'grupoController@buscarPeriodos')->middleware('auth');
Route::get('/grupos/buscar/{idgrupos?}', 'grupoController@buscarGrupos')->middleware('auth');
Route::get('/grupos/evaluaciones/{idevaluacion?}', 'grupoController@buscarEvaluaciones')->middleware('auth');
Route::post('/grupos/finalizar', 'grupoController@finalizarGrupo')->middleware('auth');

Route::get('/grupos/estudiantes/{idgrupos?}', 'estudianteGrupoController@show')->middleware('auth');
Route::get('/estudiantegrupo/{idgrupos?}', 'estudianteGrupoController@busquedaEstudiante')->middleware('auth');
Route::post('/estudiantegrupo/create', 'estudianteGrupoController@create')->middleware('auth');
Route::put('/estudiantegrupo/cambiarEstado/{id?}', 'estudianteGrupoController@cambiarEstado')->middleware('auth');
Route::put('/estudiantegrupo/createPonderacion', 'estudianteGrupoController@createPonderacion')->middleware('auth');

Route::group(['middleware'=>['adminDocente:1,2']],function(){
Route::get('/grupos/notas/{idgrupos?}', 'notaController@show')->middleware('auth');
Route::put('/estudiantegrupo/createNota', 'notaController@createNota')->middleware('auth');
});
Route::get('/grupos/traspasos', 'grupoController@showTraspasoGrupo')->name('traspaso')->middleware('auth');
Route::post('/grupos/obtenerGruposTraspaso', 'grupoController@obtenerGruposTraspaso')->middleware('auth');
Route::post('/grupos/obtenerEstudiantes', 'grupoController@obtenerEstudiantes')->middleware('auth');
Route::put('/grupos/transferirEstudiante', 'grupoController@transferirEstudiante')->middleware('auth');

Route::get('/record', 'userRecordEstudianteController@show')->name('record')->middleware('auth');
Route::get('/record/{ididiomas?}', 'userRecordEstudianteController@showParametros')->middleware('auth');
Route::put('/record/filtrar', 'userRecordEstudianteController@filtrar')->middleware('auth');

Route::get('/notas', 'userNotasEstudianteController@show')->name('notas')->middleware('auth');

////////////////////////////RESET PASSWORD IS ADDED BY DEFAULT NO NEED TO SCRIP IT /////////////////////////////////////////
//Route::get('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');//yas esta esta pero continuo aon tuto
//Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
//Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
////////////////////////////////////////////////////////////////////////////////////

//Route::get('/modalidad', 'modalidadController@show')->name('modalidadShow')->middleware('auth');


//Route::post('/noticiaForm/create', 'noticiaController@create')->name('noticiaCreate')->middleware('auth');

/////////////////////////ESTOS RECURSOS SOLO SERAN AUTH YA ESTAN VALIDADOS EN EL CONTROLADOR LOS USUARIOS//////////////////////////
Route::get('/perfil', 'profileController@showProfile')->name('profile')->middleware('auth');
Route::get('/seguridad/password', 'profileController@showCambiarPassword')->name('seguridadPassword')->middleware('auth');
Route::put('/seguridad/updatePassword', 'profileController@updatePassword')->middleware('auth');
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Route::get('/perfil/cursadoEstudiante', 'profileController@gruposcursadosEstudiante')->name('perfilcursadoEstudiante')->middleware('auth');
Route::get('/perfil/cursadoEstudiante/idioma/{ididioma?}', 'profileController@gruposcursadosEstudianteParametro')->name('perfilcursadoEstudianteParametro')->middleware('auth');


Route::get('/home', 'HomeController@index')->name('home');


// Ponderaciones
Route::resource('evaluaciones', 'EvaluacionesController');

// Equipo
Route::resource("equipos", "EquipoController");

//materiales
Route::resource("materiales", "MaterialDidacticoController");
Route::resource('prestamos', 'PrestamoController');

Route::post('/prestamos-search', 'PrestamoController@searchTipoEquipo');


// Rutas nuevas
Route::post("/docente/deleteEquipo", "docenteController@deleteEquipo");
Route::post("/docente/addEquipo", "docenteController@addEquipoDocente");
Route::post("/docente/entregarEquipo", "docenteController@entregarEquipo");
Route::post("/docente/addPrestamo", "docenteController@addEquipoPrestamo");
Route::get("/docente/{id}", "docenteController@showData")->name("prestamo_docente");
Route::get("/docente/{id}/viewsHistory", "docenteController@viewHistoryPrestamo")->name("history_prestamos");


// para el prestamos de libro por grupo, para el docente
Route::get('/docente/{id}/materiales', 'docenteController@materiales')->name('docente_materiales');
Route::post('/docente/addMaterialDocente', 'docenteController@addMaterialDocente');
Route::post('/sendMaterialDidactico', "docenteController@sendMaterialDidactico");
Route::get("/docente/{id}/materialHistory", 'docenteController@viewHistoryMaterial')->name("docente_prestamos");


// busquedas
Route::get('/equipos/{id}/search', 'EquipoController@search');
Route::get('/materiales/{id}/search', 'MaterialDidacticoController@search');

app/Equipo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Equipo extends Model
{
  public $table = 'equipos';
  public function docente() {
    return $this->belongsToMany("App\docente");
  }
  public function tipoEquipo()
  {
    return $this->belongsTo("App\TipoEquipo");
  }
}

app/Http/Controllers/EquipoController.php
<?php
namespace App\Http\Controllers;

use App\Equipo;
use App\TipoEquipo;
use App\Configuraciones;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EquipoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        /*INSERT INTO `tipo_equipo` (`id`, `nombre_tipo`, `created_at`, `updated_at`) VALUES
        (1, 'Grabadora', '2019-12-28 01:53:47', '2019-12-28 01:53:47'),
        (2, 'Laptop', '2019-12-28 01:53:47', '2019-12-28 01:53:47');*/
        if(count(TipoEquipo::get())== 0 ){
            TipoEquipo::create([
                'nombre_tipo'=>'Grabadora',
            
            ]);
            TipoEquipo::create([
                'nombre_tipo'=>'Laptop',
            ]); 
        
        }
        $equipos = Equipo::all();
        return view('equipos.showEquipo', compact('equipos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $all = TipoEquipo::all();
        return view('equipos.create', [
            'tipos' => $all
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $configuracion = Configuraciones::find(1);
        $codigoEquipo = $this->generateCodigoEquipo($configuracion->cantidad);

        $equipo = new Equipo;
        $equipo->codigo = $codigoEquipo;
        $equipo->estado = 1;
        $equipo->observacion = '';
        $equipo->marca = $request->get('marca');
        $equipo->nserie = $request->get('serie');
        $equipo->precio = $request->get('precio');
        $equipo->modelo = $request->get('modelo');
        $equipo->fechaAd = $request->get('fechaAquisicion');
        $equipo->description = $request->get('descripcion');
        $equipo->tipo_equipo_id = $request->get('tipo_equipo');
        $equipo->save();

        $configuracion->cantidad += 1;
        $configuracion->save();
        
        return redirect('/equipos');
    }

    private function generateCodigoEquipo($valor) {
        $inicio = "EQ";
        $complemento = "00".$valor;

        if($valor > 9)
            $complemento = "0".$valor;
        else if($valor > 99)
            $complemento = $valor;
        return "$inicio$complemento";
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function show(Equipo $equipo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function edit(Equipo $equipo)
    {
        $all = TipoEquipo::all();
        return view('equipos.edit', [
            'item'  => $equipo,
            'tipos' => $all
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Equipo $equipo)
    {
        $equipo->description = $request->get('descripcion');
        $equipo->marca = $request->get('marca');
        $equipo->modelo = $request->get('modelo');
        $equipo->nserie = $request->get('serie');
        $equipo->fechaAd = $request->get('fechaAquisicion');
        $equipo->precio = $request->get('precio');
        $equipo->tipo_equipo_id = $request->get('tipo_equipo');
        $equipo->save();

        return redirect("/equipos");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Equipo $equipo)
    {
        //
    }

    public function search($id)
    {
        return Equipo::find($id);
    }
}

resources/views/equipos/create.blade.php
@extends('layouts.shared.appplantilla')

@section('content')
<div id="page-head">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="demo-pli-home"></i></a></li>
    <li><a href="{{ route('equipos.index') }}">Equipos</a></li>
    <li class="active">Agregar equipo</li>
  </ol>
</div>
<div id="page-content">
  <div class="col-sm-12">
    <div class="panel"  style="border: 1px bold #ccc; box-shadow: 2px 2px #bbb !important">
      <div class="panel-heading bg-gray-dark">
      
        <h3 class="panel-title "><p align="left" class="text-m text-bold media-heading mar-no text-main bg"> <strong style="font-size: 14px;">AGREGAR EQUIPO</strong></p></h3>
      
      </div>
      <form action="{{ route('equipos.store') }}" method="POST">
        {{ csrf_field() }}
        <div class="panel-body"  style="background-image: linear-gradient(#eeeeee 0.5%, #ffffff 0%);min-height: 400px;">
          <div class="row">
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Marca: </label>
                <input class="form-control" type="text" required name="marca" id="marca" />
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Modelo: </label>
                <input type="text" required class="form-control" name="modelo" id="modelo" />
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Tipo del Equipo: </label>
                <select class='form-control' name="tipo_equipo" id="tipo_equipo">
                  @foreach ($tipos as $item)
                    <option value="{{ $item->id }}">{{ $item->nombre_tipo }}</option>
                  @endforeach
                </select>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Serie: </label>
                <input type="text" required class="form-control" name="serie" id="serie" />
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group" id="datePicker">
                <label class="control-label">Fecha de adquisicion: </label>
                <div class="input-group">
                  <input type="date" required class="form-control" name="fechaAquisicion" id="fechaAquisicion" />
                  <span class="input-group-addon"><i class="demo-pli-calendar-4"></i></span>
                </div>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Precio: </label>
                <input type="number" required step="any" class="form-control" name="precio" id="precio" />
              </div>
            {{-- </div>
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Estado: </label>
                <select required name="estado" id="estado" class="form-control">
                  <option value="1">DISPONIBLE</option>
                  <option value="2">PRESTADO</option>
                  <option value="0">DE-BAJA</option>
                </select>
              </div>
            </div> --}}
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <label class="control-label">Descripcion: </label>
                <textarea required name="descripcion" id="descripcion" cols="5" rows="5" class="form-control"></textarea>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-footer text-right">
          <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@section('script')
  
  <script type="text/javascript">
       $(document).ready(function(){
        $.niftyNav('expand');
       
       });
    </script>
  
    
  
    @endsection

resources/views/equipos/edit.blade.php
@extends('layouts.shared.appplantilla')

@section('content')
<div id="page-head">
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="demo-pli-home"></i></a></li>
    <li><a href="{{ route('equipos.index') }}">Equipos</a></li>
    <li class="active">Editar equipo</li>
  </ol>
</div>
<div id="page-content">
  <div class="col-sm-12">
    <div class="panel" style="border: 1px bold #ccc; box-shadow: 2px 2px #bbb !important">
      <div class="panel-heading">
        <h3 class="panel-title bg-mint"><p align="left" class="text-m text-bold media-heading mar-no text-main bg"> <strong style="font-size: 14px;color:white">EDITAR EQUIPO</strong></p></h3>
      
      </div>
      <form action="{{ route("equipos.update", ["id" => $item->id ]) }}" method="POST">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PUT" />
        <div class="panel-body" style="background-image: linear-gradient(#eeeeee 0.5%, #ffffff 0%);min-height: 350px;">
          <div class="row">
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Marca: </label>
                <input value="{{ $item->marca }}"
                  class="form-control" type="text" required name="marca" id="marca" />
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Modelo: </label>
                <input required type="text" value="{{ $item->modelo }}"
                  class="form-control" name="modelo" id="modelo" />
              </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <label class="control-label">Serie: </label>
                <input required type="text" value="{{ $item->nserie }}"
                  class="form-control" name="serie" id="serie" />
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group" id="datePicker">
                <label class="control-label">Fecha de adquisicion: </label>
                <div class="input-group">
                  <input type="date" value="{{ date("Y-m-d", strtotime($item->fechaAd)) }}" required
                    class="form-control" name="fechaAquisicion" id="fechaAquisicion" />
                  <span class="input-group-addon"><i class="demo-pli-calendar-4"></i></span>
                </div>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <label class="control-label">Precio: </label>
                <input type="number" value="{{ $item->precio }}" required
                  step="any" class="form-control" name="precio" id="precio" />
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
               
                <label class="control-label">Tipo de equipo: </label>
                <select name="tipo_equipo" id="tipo_equipo" class="form-control">
                  @foreach ($tipos as $tipo)
                    <option value="{{$tipo['id']}}"
                      {{ $tipo['id'] === $item->tipoEquipo->id ? 'selected' : '' }}>{{ $tipo->nombre_tipo }}
                    </option>
                  @endforeach
                </select>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <label class="control-label">Descripcion: </label>
                <textarea required name="descripcion" 
                id="descripcion" cols="5" rows="5" 
                  class="form-control">{{ $item->description }}</textarea>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-footer text-right">
          <button class="btn btn-mint" type="submit">Editar</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection
@section('script')
  <script type="text/javascript">
    $(document).ready(function(){
    $.niftyNav('expand');
    
    });
    </script>
@endsection

resources/views/equipos/formEquipo.blade.php
<form class="panel-body form-horizontal form-padding" id="frm" name="frmsocios" action="/socios/create" method="post">
    <input type="hidden" id="form_id" name="form_id" value="0">

    <div class="panel">

        <div class="card-body "></div>
        <div class="col-lg-1">

        </div>
        <div class="col-lg-10 ">

            {{-- <div class="row">
        <h6 class="text-main" style="font-weight:bold;">Formulario</h6></div>       --}}
            <div id="nombrediv" class="form-group @if($errors->has('nombre')) has-danger @endif">
                <label for="example-text-input" class="col-md-3 control-label text-main text-bold "> Código: *</label>
                <div class="col-md-7 ">

                    {{-- Token ue genera laravel es obligatorio
            debido a laraevl provee seguridad y da el toen
            para que lo econozca que es nuestro formulario
            {{ csrf_field() }} --}}

                    <input class="form-control" type="text" placeholder="Ingrese codigo de equipo " id="codigo"
                        name="codigo">
                    {{-- @if($errors->has('nombre'))
               @foreach($errors->get('nombre') as $error)--}}
                    <div id="codigofeed" class="form-control-feedback"></div>
                    {{--  @endforeach
            @endif --}}
                </div>
            </div>

            <div id="descripciondiv" class="form-group">
                <label for="example-number-input"
                    class="col-md-3 control-label text-main text-bold ">Descripción:*</label>
                <div class="col-md-7  ">
                    <textarea class="form-control" type="text" id="descripcion" name="descripcion" value=""
                        rows="2"></textarea>
                    <div id="descripcionfeed" class="form-control-feedback"></div>
                </div>
            </div>
            <div id="marcadiv" class="form-group">
                <label for="example-number-input" class="col-md-3 control-label text-main text-bold ">Marca:*</label>
                <div class="col-md-7  ">
                    <input class="form-control" type="text" placeholder="Ingrese la marca del equipo" id="marca"
                        name="marca">
                    <div id="marcafeed" class="form-control-feedback"></div>
                </div>
            </div>
            <div id="modelodiv" class="form-group">
                <label for="example-number-input" class="col-md-3 control-label text-main text-bold ">Modelo:*</label>
                <div class="col-md-7  ">
                    <input class="form-control" type="text" placeholder="Ingrese Numero de Modelo" id="modelo"
                        name="modelo">
                    <div id="modelofeed" class="form-control-feedback"></div>
                </div>
            </div>
            <div id="telefonodiv" class="form-group">
                <label for="example-number-input" class="col-md-3 control-label text-main text-bold ">N° Serie:*</label>
                <div class="col-md-7  ">
                    <input class="form-control" type="text" placeholder="Ingrese Numero de Serie" id="nserie"
                        name="nserie">
                    <div id="nseriefeed" class="form-control-feedback"></div>
                </div>
            </div>
            <div id="telefonodiv" class="form-group">
                <label for="example-number-input" class="col-md-3 control-label text-main text-bold ">Fecha de
                    Adquisición:*</label>
                <div class="col-md-7  ">
                    <input class="form-control" type="date" id="fechaAd" name="fecha">
                    <div id="fechaAdfeed" class="form-control-feedback"></div>
                </div>
            </div>
            <div id="telefonodiv" class="form-group">
                <label for="example-number-input" class="col-md-3 control-label text-main text-bold ">Precio: $
                    *</label>
                <div class="col-md-7  ">
                    <input class="form-control" type="text"
                        placeholder="Ingrese el precio de adquisicion, de ser donado ingrese valor 0" id="precio"
                        name="obse">
                    <div id="preciofeed" class="form-control-feedback"></div>
                </div>
            </div>
            <div id="telefonodiv" class="form-group">
                <label for="example-number-input"
                    class="col-md-3 control-label text-main text-bold ">Observación:*</label>
                <div class="col-md-7  ">
                    <input class="form-control" type="text" placeholder="Ingrese alguna observacion sobre el equipo"
                        id="observacion" name="obse">
                    <div id="observacionfeed" class="form-control-feedback"></div>
                </div>
            </div>
            {{-- <div id="apellidodiv" class="form-group">
        <label for="example-text-input" class="col-md-3 control-label text-main text-bold ">Apellido: *</label>
        <div class="col-md-7">
            <input class="form-control" type="text" value="" id="apellido" name="apellido">
            <div id="apellidofeed" class="form-control-feedback"></div>
        </div>
    </div>
    <div id="fechaNacdiv" class="form-group">
        <label for="example-date-input" class="col-md-3 control-label text-main text-bold">Email: *</label>
        <div class="col-md-7">
            <input class="form-control " type="date"  placeholder="ejemplo@algo.com" id="email" name="fechaNac">
            <div id="fechaNacfeed" class="form-control-feedback"></div>

        </div>
    </div>
    <div id="duidiv" class="form-group row">
        <label for="example-number-input" class="col-md-3 control-label text-main text-bold">DUI: *</label>
        <div class="col-md-7">
            <input class="form-control" type="text"  id="dui" name="dui">
            <div id="duifeed" class="form-control-feedback"></div>
        </div>
    </div>

    <div id="telefonodiv" class="form-group row">
        <label for="example-number-input" class="col-md-3 control-label text-main text-bold">Teléfono</label>
        <div class="col-md-7 ">
            <input class="form-control" type="number"  id="telefono" name="telefono">
            <div id="telefonofeed" class="form-control-feedback"></div>
        </div>
    </div>--}}



        </div>

    </div>
</form>